services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: videodb
      POSTGRES_USER: videouser
      POSTGRES_PASSWORD: videopass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://videouser:videopass@db:5432/videodb
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: